### ISSUE TITLE
Performance of select statements after reaching shared_buffers threshold

### ISSUE THREAD

**Issue by xcu** [timescale/pgvectorscale#144]
Hi,

I am running some tests to check performance of DiskANN and I have noticed that, once the index size exceeds the limit allocated in shared_buffers, performance of select statements really drops (as in, 10x slower). I was under the impression that one of the key points of DiskANN is that the index did not need to be fully in memory to perform well, so perhaps I'm missing something in the config? I am using the default parameters both for index building and searching.

**Comment by cevian** [comment]
Sorry for the delayed response.

Your queries will definitely slow down after shared_buffers is exceeded by the index. They may be still good enough depending on the speed of the SSD. In our 50M pinecone comparison (https://www.timescale.com/blog/pgvector-vs-pinecone/) the dataset size was definitely bigger than the ram (128GB). Namely the total relation size was 223GB. But the index itself was smaller (32GB) due to SBQ.

If you provide some more info on your setup perhaps we can help some more. Also note that rebuilding the index may make it smaller. There was a bug with inserts causing bloat which was fixed in #148 due out in the next release. But the workaround for now is an index rebuild.

**Comment by alejandrodnm** [comment]
Hey @xcu I'm going to close the issue, but feel free to re-opening it if you want to continue the conversation.

Thanks :)

**Comment by xcu** [comment]
Hey @cevian , thanks for the thorough response! That makes sense. I haven't tried rebuilding indexes but I'll give it a go. I get a compression of ~4.6x compared to the almost 7x you get in the index size related to the dataset, so if I can achieve the same factor it would be great.

I thought diskANN managed to sort of maintain performance even when it had to go fetch embeddings from disk, although to be honest now that I think about it I'm not sure how that could be even possible :) 

Regarding the setup, I'm using casia webface dataset + random embeddings, up to 20M. Embeddings have size of 512. The Postgres host has 8GB of memory and 4GB of shared buffers, and 8 cores.

Apologies for the late response, paternity is keeping me away from computers these months.
